#!/usr/bin/php -q
<?php  //  -*- mode:php; tab-width:2; c-basic-offset:2; -*-


$CAPTAINHOOK_PATH = getenv('CAPTAINHOOK_PATH');
if ($CAPTAINHOOK_PATH === false) {
  if (is_file(getcwd().'/conf/general.conf')) $CAPTAINHOOK_PATH=getcwd();
  else $CAPTAINHOOK_PATH = "/home/web/rcresponsable/captainhook";
}

function _readline($prompt = '') {
  echo $prompt;
  return rtrim(fgets(STDIN), "\n");
}

$scriptDir = dirname(__FILE__);

if (!is_dir($CAPTAINHOOK_PATH)) {
	echo "Captainhook core not found, please edit me and set \$CAPTAINHOOK_PATH variable.\n";
	exit;
}

if (!is_file($CAPTAINHOOK_PATH.'/conf/general.conf') || !is_readable($CAPTAINHOOK_PATH.'/conf/general.conf')) {
	echo "Captainhook config file not found.\n";
	exit;
}

require($CAPTAINHOOK_PATH.'/core/Core.php');
\core\Core::init();

if (\core\Core::$db->fetchOne("SELECT COUNT(*) FROM pg_language WHERE lanname = 'plpgsql'") == 0) {
	echo "/!\ Error\n";
	echo "plpgsql language is not installed.\n";
	echo "Example: createlang plpgsql captainhook_database_name\n";
	echo "See: http://www.postgresql.org/docs/8.3/static/xplang-install.html\n";
	echo "Exiting.\n";
	exit;
}

if (\core\Core::$db->fetchOne("SELECT COUNT(*) from pg_proc WHERE proname = 'box3d'") == 0) {
	echo "\n/!\ Error\n";
	echo "Postgis is not installed.\n\n";
	echo "For example with Debian (with postgresql 8.4, replace by 9.1 if you use 9.1): \n";
	echo "apt-get install postgresql-8.4-postgis (and restart Postgresql server)\n";
	echo "As postgresl user do:\n";
	echo "psql captainhook-database < /usr/share/postgresql/8.4/contrib/postgis-1.5/postgis.sql\n";
	echo "psql captainhook-database < /usr/share/postgresql/8.4/contrib/postgis-1.5/spatial_ref_sys.sql\n";
	echo "Change spatial_ref_sys and geometry_columns sequences's owner::\n";
	echo "alter table spatial_ref_sys owner to captainhook-user-name\n";
	echo "alter table geometry_columns  owner to captainhook-user-name\n";
	exit;
}

echo "Everything is ok\n";

exit;
