#!/usr/bin/php -q
<?php  //  -*- mode:php; tab-width:2; c-basic-offset:2; -*-


$CAPTAINHOOK_PATH = getenv('CAPTAINHOOK_PATH');
if ($CAPTAINHOOK_PATH === false) {
  if (is_file(getcwd().'/conf/general.conf')) $CAPTAINHOOK_PATH=getcwd();
  else $CAPTAINHOOK_PATH = "/home/web/rcresponsable/captainhook/";
}

$scriptDir = dirname(__FILE__);

if (!is_dir($CAPTAINHOOK_PATH)) {
	echo "Captainhook core not found, please edit me and set \$CAPTAINHOOK_PATH variable.\n";
	exit;
}

if (!is_file($CAPTAINHOOK_PATH.'/conf/general.conf') || !is_readable($CAPTAINHOOK_PATH.'/conf/general.conf')) {
	echo "Captainhook config file not found.\n";
	exit;
}

require($CAPTAINHOOK_PATH.'/core/Core.php');
\core\Core::init();

$outp = "Code de l'aliment; Nom de l'aliment\n";
foreach(\mod\repasrc\Foodstuff::searchAll() as $fs) {
	$label = (!empty($fs['synonym_id'])) ? $fs['synonym'] : $fs['label'];
	$outp.= "$fs[code];$label;\n";
}

file_put_contents(dirname(__FILE__).'/../files/liste_des_aliments.csv', $outp);

exit;
